# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMcppARMSI <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min) {
    .Call('rMSWITCH_EMcppARMSI', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min)
}

EMcppARMSIA <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min) {
    .Call('rMSWITCH_EMcppARMSIA', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min)
}

EMcppARMSIAH <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min) {
    .Call('rMSWITCH_EMcppARMSIAH', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min)
}

EMcppARMSIH <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min) {
    .Call('rMSWITCH_EMcppARMSIH', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min)
}

EMcppARMSIHQuZhuo <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min) {
    .Call('rMSWITCH_EMcppARMSIHQuZhuo', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min)
}

EMcppARMSIQuZhuo <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min) {
    .Call('rMSWITCH_EMcppARMSIQuZhuo', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min)
}

EMcppARMSM <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_EMcppARMSM', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp)
}

EMcppARMSMAH <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_EMcppARMSMAH', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp)
}

EMcppARMSMH <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_EMcppARMSMH', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, beta0_rcpp, mu0_rcpp, sigma0_rcpp, gamma_dependent0_rcpp, gamma_independent0_rcpp, transition_probs0_rcpp, initial_dist0_rcpp, maxit, epsilon, transition_probs_min, transition_probs_max, sigma_min, state_conversion_mat_rcpp)
}

LikelihoodMSIAR <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp) {
    .Call('rMSWITCH_LikelihoodMSIAR', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp)
}

LikelihoodMSIAROld <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp) {
    .Call('rMSWITCH_LikelihoodMSIAROld', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp)
}

LikelihoodMSMAR <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_LikelihoodMSMAR', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp)
}

LikelihoodMSMAROld <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_LikelihoodMSMAROld', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp)
}

LikelihoodsMSIAR <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp) {
    .Call('rMSWITCH_LikelihoodsMSIAR', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp)
}

LikelihoodsMSIAROld <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp) {
    .Call('rMSWITCH_LikelihoodsMSIAROld', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp)
}

LikelihoodsMSMAR <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_LikelihoodsMSMAR', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp)
}

LikelihoodsMSMAROld <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_LikelihoodsMSMAROld', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp)
}

PosteriorProbsMSIAR <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp) {
    .Call('rMSWITCH_PosteriorProbsMSIAR', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, transition_probs_rcpp, initial_dist_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp)
}

PosteriorProbsMSMAR <- function(y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp) {
    .Call('rMSWITCH_PosteriorProbsMSMAR', PACKAGE = 'rMSWITCH', y_rcpp, y_lagged_rcpp, z_dependent_rcpp, z_independent_rcpp, z_dependent_lagged_rcpp, z_independent_lagged_rcpp, transition_probs_rcpp, initial_dist_extended_rcpp, beta_rcpp, mu_rcpp, sigma_rcpp, gamma_dependent_rcpp, gamma_independent_rcpp, state_conversion_mat_rcpp)
}

